M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-08-10T04:03:37+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-10T04:03:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X124.795Y-74.794
X130.575Y-74.794
M30
